### ISSUE TITLE
Diseño de vista "Registro de productos"

### ISSUE THREAD

**Issue by Yas-Mtz** [Yas-Mtz/Almacen_UACM2#43]

**Comment by VRFT** [comment]
Diseño de vista de registro producto nueva. 
Se hagrego un nuevo .css y se corrigio una linea de setting.py

STATIC_URL = '/static/' #modificada de'static/'



[css de registro de productos.txt](https://github.com/Yas-Mtz/Almacen_UACM2/files/14727601/css.de.registro.de.productos.txt)
