### ISSUE TITLE
Prueba de interfaz "Registro de productos"

### ISSUE THREAD

**Issue by Yas-Mtz** [Yas-Mtz/Almacen_UACM2#50]

**Comment by VRFT** [comment]
Se han agregado dos nuevas fucnionalidades a esta interfaz, 1.- El usuario podra consultar los productos ya registrados en la base de datos con el nuevo boton de Consultar Productos y 2.- El podeer escanear los productos, se ha agregado esta funcioanalidad con la finalidad de hacer un poco mas agil el registro de productos.

Archivos modificados para realizar estas dos funcionlñaidades:


views.py

def consultar_productos(request):
    print("Entrando a la vista consultar_productos")

    try:
        productos = Producto.objects.all()  # Obtener todos los productos
    except Exception as e:
        # Manejar el error si ocurre al consultar la base de datos
        return render(request, 'error.html', {'error_message': str(e)})

    return render(request, 'consultar_productos.html', {'productos': productos})

urls.py

path('consultar-productos/', views.consultar_productos, name='consultar_productos'),

HTML (registrar_productos.html)

<a href="{% url 'consultar_productos' %}" class="consultar-link">
            <button type="button">Consultar Productos</button>

y se creo un nuevo HTML (consultar_productos.html)

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar Productos</title>
    
    <link rel="preload" href="/static/Estilos/styles8.css" as="style">
    <link href="/static/Estilos/styles8.css" rel="stylesheet">
</head>
<body>
    <h1>Productos Registrados</h1>
    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in productos %}
                <tr>
                    <td>{{ producto.id_producto }}</td>
                    <td>{{ producto.nombre_producto }}</td>
                    <td>{{ producto.cantidad }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</body>
</html>


Y por ultimo se agrego la funcionalidad de QR en el html (registrar_productos.html)

<script src="https://unpkg.com/html5-qrcode"></script>
    <script>
        var scannerVisible = false;
        var htmlScanner = null;

        function toggleScanner() {
            if (scannerVisible) {
                htmlScanner.stop();
                document.getElementById('scannerContainer').style.display = 'none';
                scannerVisible = false;
            } else {
                htmlScanner.render(onScanSuccess);
                document.getElementById('scannerContainer').style.display = 'block';
                scannerVisible = true;
            }
        }

        function limpiarCampos() {
            document.getElementById("id").value = "";
            document.getElementById("nombre").value = "";
            document.getElementById("cantidad").value = "";
        }

        function domReady(fn) {
            if (document.readyState === "complete" || document.readyState === "interactive") {
                setTimeout(fn, 1);
            } else {
                document.addEventListener("DOMContentLoaded", fn);
            }
        }

        domReady(function() {
            htmlScanner = new Html5QrcodeScanner(
                "reader", { fps: 10, qrbox: 350 }
            );
        });

        function onScanSuccess(decodedText, decodedResult) {
            var resultContainer = document.getElementById('result');
            if (resultContainer) {
                resultContainer.innerHTML = 'Tu QR es: ' + decodedText;
                // Redirigir a la página después de leer el QR
                window.location.href = decodedText; // Cambia esta línea según el formato de la URL que devuelve tu lector de QR
            }
        }
    </script>

**Comment by VRFT** [comment]
Se implemento correctamente la funcionalidad de extracción de datos del QR una vez escaneados por la camara o por una imagen almacenada en el dispositivo. Se agregaron nuevas lineas en el script para esta nueva funcionalidad.

function onScanSuccess(decodedText, decodedResult) {
            // Parsamos el texto del código QR, y extraemos el ID, nombre y cantidad
            var qrData = decodedText.split("\n");
            var idProducto = qrData[0].split(": ")[1];
            var nombreProducto = qrData[1].split(": ")[1];
            var cantidad = qrData[2].split(": ")[1];

            // Llenamos la informacion del formulario con los extraido del QR
            document.getElementById("id").value = idProducto;
            document.getElementById("nombre").value = nombreProducto;
            document.getElementById("cantidad").value = cantidad;

            // Ocultar el escáner de QR después de llenar los campos
            toggleScanner();
