### ISSUE TITLE
Desarrollo de funcionalidad "Registro de productos"

### ISSUE THREAD

**Issue by Yas-Mtz** [Yas-Mtz/Almacen_UACM2#58]

**Comment by VRFT** [comment]
Se quiere implementar un stored procedure en la base para insertar datos de los productos, tambien se ha modificado parte de la vista para que pueda llamar este procedimiento e insertar los datos, aun no ha quedado al cien. Datos modificados:

CREATE PROCEDURE InsertarProducto(
    IN p_id INT,
    IN p_nombre VARCHAR(255),
    IN p_cantidad INT
)
BEGIN
    INSERT INTO Producto (id, nombre, cantidad) 
    VALUES (p_id, p_nombre, p_cantidad);
END 

#Apartado de metodo FactoryMethod
def registrar_producto(request):
    if request.method == 'POST':
        # Obtener los datos del formulario
        id_producto = request.POST['id_producto']
        nombre_producto = request.POST['nombre_producto']
        cantidad_producto = request.POST['cantidad_producto']
        
        # Llamar al procedimiento almacenado para insertar el producto en la base de datos
        try:
            conn = mysql.connector.connect(user='tu_usuario', password='tu_contraseña',
                                      host='tu_host', database='tu_base_de_datos')
            cursor = conn.cursor()
            
            cursor.callproc('InsertarProducto', [id_producto, nombre_producto, cantidad_producto])
            conn.commit()
            cursor.close()
            conn.close()
            # Redirigir a una página de éxito
            return render(request, 'exito.html')
            
        except mysql.connector.Error as err:
            # Manejar el error de alguna manera
            print("Error al insertar el producto:", err)
            # Redirigir a una página de error
            return render(request, 'error.html')
    
    else:
        # Si el método HTTP no es POST, renderizar el formulario
        return render(request, 'registro_producto.html')

**Comment by VRFT** [comment]
Para este punto de avanece, se hizo una pequeña reestructuración del codigo, se quito el patron de diseño implementado para este apartado (factory methodo). Se modifico el stored procedure ya que tenia un error de dirección de tabla, se ha modificado la vista eliminando restos del metodo y llamando al stored procedure, tambien se modifico el html para que al llenar el formulario se agregen a la base de datos correctamente.

**Comment by VRFT** [comment]
Ultimas modificaciones hechas, ya el apartado registra en la base de datos, faltan pequeños detalles

Stored Procedure (se corrigio la direccion de la tabla a la que apuntaba):

CREATE DEFINER=`root`@`localhost` PROCEDURE `RegistrarProducto`(
    IN p_id INT,
    IN p_nombre VARCHAR(255),
    IN p_cantidad INT
)
BEGIN
    INSERT INTO almacen_app_producto (id_producto, nombre_producto, cantidad)
    VALUES (p_id, p_nombre, p_cantidad);
END

Models.py (eliminación del metodo factory):

class Producto(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nombre_producto = models.CharField(max_length=255)
    cantidad = models.IntegerField()


Views.py (Correción esta no llamaba de la manera correcta al stored procedure):

from django.db import connection
from django.contrib import messages

def registrar_productos(request):
    print("Entrando a la vista registrar_productos")

    if request.method == 'POST':
        id_producto = request.POST.get('id')
        nombre = request.POST.get('nombre')
        cantidad = request.POST.get('cantidad')

        try:
            with connection.cursor() as cursor:
                cursor.callproc('RegistrarProducto', [id_producto, nombre, cantidad]) 
        except Exception as e:
            messages.error(request, f"Error al registrar el producto: {str(e)}")
        else:
            messages.success(request, "Producto registrado con éxito.")

    return render(request, 'registrar_productos.html')


HTML registrar productos (Hubo muchas modificaciones en este apartado ya que no registraba y se han omitido algunas cosas de versiones anteriores, ya que interfieren en la version de registro):

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrar Producto</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            margin: 0;
            background-image: url('https://www.uacm.edu.mx/portals/_default/skins/wcga-uacm/images/Plantel.jpg');
            background-size: cover;
            background-position: center top;
            background-repeat: no-repeat;
            display: flex;
            flex-direction: column; /* Alinea los elementos verticalmente */
            align-items: center;
            height: 100vh;
            backdrop-filter: blur(4px); /* Aplica el desenfoque a la capa */
        }
        
        h1 {
            margin-top: 50px; /* Margen superior para centrar el título */
            text-align: center;
        }
        
        /* Estilos adicionales para el formulario */
        form {
            background-color: rgba(255, 255, 255, 0.7); /* Fondo semi-transparente */
            width: 60%; /* Ancho del formulario */
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 10px;
            max-width: 400px;
            margin-top: 20px; /* Margen superior para centrar el formulario */
            margin-left: auto; /* Ajusta el formulario más a la izquierda */
            margin-right: auto; /* Ajusta el formulario más a la derecha */
        }
        
        form label,
        form input,
        form button {
            display: block;
            margin: 15px auto; /* Ajusta la distancia entre los elementos del formulario */
        }
        
        /* Establece el borde de los cuadros de texto como azul */
        form input {
            width: calc(100% - 30px);
            border: 2px solid #3c80e7; /* Cambia el grosor y el color del borde */
            border-radius: 5px;
            padding: 10px; /* Ajusta el relleno del formulario */
            font-size: 15px; /* Ajusta el tamaño del texto en el formulario */
            transition: border-color 0.3s ease; /* Efecto de transición en el borde */
        }
        
        form input:focus {
            border-color: #3498db; /* Cambia el color del borde al enfocar el elemento */
        }
        
        form button {
            background-color: #3498db; /* Azul claro */
            color: white;
            border: none;
            border-radius: 5px;
            padding: 12px 20px; /* Ajusta el tamaño del botón */
            cursor: pointer;
            margin-right: 10px;
            transition: background-color 0.3s ease; /* Efecto de transición en el color de fondo */
        }
        
        form button#guardar {
            background-color: #3498db; /* Azul claro */
        }
        
        form button#guardar:hover {
            background-color: #5dade2; /* Azul claro más intenso al pasar el ratón */
        }
        
        form button#limpiar {
            background-color: #e74c3c; /* Rojo menos intenso */
            color: white;
        }
        
        form button#limpiar:hover {
            background-color: #d9534f; /* Rojo menos intenso más intenso al pasar el ratón */
        }
    </style>
</head>
<body>
    <h1>Registrar Producto</h1>
    <form method="POST">
        {% csrf_token %}
        <label for="id">ID del Producto:</label>
        <input type="text" id="id" name="id">
        <label for="nombre">Nombre del Producto:</label>
        <input type="text" id="nombre" name="nombre">
        <label for="cantidad">Cantidad:</label>
        <input type="text" id="cantidad" name="cantidad">
        <button type="submit" id="guardar">Registrar Producto</button>
        <button type="button" id="limpiar" onclick="limpiarCampos()">Limpiar Campos</button>
    </form>

    <script>
        function limpiarCampos() {
            document.getElementById("id").value = "";
            document.getElementById("nombre").value = "";
            document.getElementById("cantidad").value = "";
        }
    </script>
</body>
</html>


Con estas modificaciones el apartado de registro de productos ya hace un correcto uso del procedure para el registro en mysql.
